config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :records do
    resources :tracks
  end

  resources :artists do
    collection do
      get "/:id/records", action: "records", as: "records"
    end
  end

end

app/models/artist.rb
class Artist < ActiveRecord::Base
  has_many :records
  has_many :tracks, through: :records
end

app/models/record.rb
class Record < ActiveRecord::Base
  mount_uploader :avatar, AvatarUploader
  belongs_to :artist
  has_many :tracks
  accepts_nested_attributes_for :tracks
end

app/models/track.rb
class Track < ActiveRecord::Base
  belongs_to :record
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

  def index
    @artists = Artist.all
  end
  
  def new
    @artist = Artist.new
  end

  def show
  end

  def create
    @artist = Artist.create(artist_params)
    redirect_to "/records/new"
  end

  def records
    @artist = Artist.find(params[:id])
    @records = @artist.records.all
  end

  protected

  def artist_params
    params.require(:artist).permit(:id, :name)
  end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController

  before_filter :load_record, only: [:show, :edit, :update, :destroy]

  def index
    @records = Record.all
  end

  def new
    @record = Record.new
  end

  def create
    @record = Record.create(record_params)
    @record.save!
    redirect_to new_record_track_path(@record)
  end

  def show
  end

  def edit
  end

  def update
    @record.update(record_params)
    redirect_to record_path(@record)
  end

  def destroy
    @record.destroy
    flash[:notice] = 'Record deleted successfully'
    redirect_to records_path
  end

  protected

  def load_record
    @record = Record.find(params[:id])
  end

  def record_params
    params.require(:record).permit(:name, :artist_id, :avatar)
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController

  def new
    @record = Record.find(params[:record_id])
    @tracks = @record.tracks
    @track = Track.new
  end

  def create
    @track = Track.new(track_params)
    respond_to do |format|
      if @track.save
        format.html { redirect_to @track, notice: 'Track was successfully created.' }
        format.js
        format.json { render json: @track, status: :created, location: @track }
      else
        format.html { render action: "new" }
        format.json { render json: @track.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @track.update(track_params)
  end

  def destroy
    @track.destroy
    flash[:notice] = 'Track deleted successfully'
  end

  protected

  def track_params
    params.require(:track).permit(:name, :record_id)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index 
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/artists/index.html.haml
.container
  - if @artists.any?
    %ul
    - @artists.each do |artist|
      %li
        = link_to artist.name, records_artists_path(artist)
  - else
    %h1
      no artists added

app/views/artists/new.html.haml
= simple_form_for @artist do |f|
  = f.input :name
  =f.button :submit

app/views/artists/records.html.haml
.container
  - if @records.any?
    %ul
    - @records.each do |record|
      %li
        = link_to record.name, record_path(record)

  - else
    %h1
      no records added
  = link_to "add a record", new_record_path

app/views/layouts/application.html.haml
!!!
%html
  %head
  %title RecordApp
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags


  %body
    = notice
    = yield

app/views/records/edit.html.haml
= simple_form_for @record do |f|
  = f.input :name
  =f.button :submit

app/views/records/index.html.haml
.container
  - if @records.any?
    %ul
    - @records.each do |record|
      %li
        = link_to record.name, record_path(record)
        = "- "
        = record.artist.name
      .li
        = image_tag record.avatar_url(:thumb) if record.avatar?
  - else
    %h1
      no records added
  = link_to "add a record", new_record_path

app/views/records/new.html.haml
= simple_form_for @record do |f|
  = f.collection_select(:artist_id, Artist.all, :id, :name, prompt: true)
  = f.input :name, label: 'Title'
  = f.file_field :avatar, label: "Upload cover"
  = f.submit 'Add Record'
  = link_to 'add artist', new_artist_path

app/views/records/show.html.haml
.container
.ul
  .li 
    = @record.name
  .li
    = @record.artist.name
  .li
    = image_tag(@record.avatar_url) if @record.avatar?
  .ul
  - @record.tracks.each do |track|
    .ul
      = track.name
  = link_to "edit", edit_record_path(@record)
  = button_to "Delete #{@record.name}", record_path(@record), method: :delete

app/views/tracks/_track.html.haml
.li
  = track.name

app/views/tracks/create.js.erb
$("<%= escape_javascript(render @track) %>").appendTo("#tracks"); 

app/views/tracks/new.html.haml
.container
.ul
  .li
    = @record.name
  .li
    = @record.artist.name
  .li
    = image_tag(@record.avatar_url) if @record.avatar?

  = simple_form_for [@record, @track], remote: true do |f|
    = f.label :name
    = f.text_field :name

    = f.submit

.ul#tracks
  = render @tracks

app/views/welcome/index.html.haml
.container
  Record Catalogue
  %ul
    %li 
      = link_to "add a record", new_record_path
    %li 
      = link_to "view all records", records_path
    %li 
      = link_to "view all artists", artists_path  